### ISSUE TITLE
Dragging bookmarlet doesn't work

### ISSUE THREAD

**Issue by mzch** [RadhiFadlillah/shiori#129]
I've added bookmarklet in commit [`4b93937`](https://github.com/RadhiFadlillah/shiori/commit/4b939379e83b34f6d9d97517a80b8dd44313bbe8). To use it, just drag the `Add new bookmark` button to your bookmark toolbar :

![Screencast](https://user-images.githubusercontent.com/6129042/41046069-e255a74e-69d3-11e8-9723-8fe0f811e168.gif)

When possible (i.e. allowed by CSP), the bookmarklet will show dialog for saving new bookmark :

![As dialog](https://user-images.githubusercontent.com/6129042/41046287-5c5a5774-69d4-11e8-8459-bf7a71297e47.png)

However, if it's not possible, the bookmarklet will redirect you to submit page :

![As submit page](https://user-images.githubusercontent.com/6129042/41046461-a60c8ac2-69d4-11e8-84af-245a070180f1.png)

Please try it out.

---

> Since you can get a SSL certificate pretty easily and for free through LetsEncrypt, you could maybe integrate auto certificate renewal...

I don't think I will do it, because :

- It adds new complexity to `shiori`. Right now I just want to focus on making shiori stable and reliable enough to use.
- When user self hosted `shiori`, they usually put it behind a web server anyway, and there are already many good web server that can fetch SSL certificate from Let'sEncrypt, e.g Caddy and nginx.

_Originally posted by @RadhiFadlillah in https://github.com/RadhiFadlillah/shiori/issues/84#issuecomment-395104974_

**Comment by mzch** [comment]
Hi,

Bookmarklet can’t be drag to toolbar on Chrome 74.0.3729.108 or later and Safari 12.1.
Is this only my own problem?

**Comment by mzch** [comment]
Sorry, I found it in About dialog.

**Comment by imjoeyli** [comment]
It doesn't work in Shiori v1.5, I can't drag add button now. How did you solve it?
