### ISSUE TITLE
Bookmark adding failed on https site with valid cert

### ISSUE THREAD

**Issue by heliostatic** [RadhiFadlillah/shiori#14]
I tried adding "https://eco.com" and got this error:
`Failed to fetch article from internet: Get https://eco.com: x509: certificate signed by unknown authority`

Here is the cert chain on the site:
![image](https://user-images.githubusercontent.com/70898/36878296-42047d9e-1d8c-11e8-8505-3407dab1aecb.png)

**Comment by heliostatic** [comment]
Looks like this originates in: https://golang.org/src/crypto/x509/verify.go#L141
And is referenced here: https://github.com/golang/go/issues/9586 and https://github.com/golang/go/issues/24147

It does look like there's something weird with the SSL cert on this site:
```
$ curl -kv https://eco.com
* Rebuilt URL to: https://eco.com/
*   Trying 50.16.250.54...
* TCP_NODELAY set
* Connected to eco.com (50.16.250.54) port 443 (#0)
* WARNING: disabling hostname validation also disables SNI.
* Unknown SSL protocol error in connection to eco.com:-9838
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to eco.com:-9838
```

**Comment by RadhiFadlillah** [comment]
This issue was moved to RadhiFadlillah/go-readability#4
