### ISSUE TITLE
How does this deal with duplicates?

### ISSUE THREAD

**Issue by karanrajpal14** [RadhiFadlillah/shiori#15]
I often find a couple of duplicate links on my Pocket account. It doesn't happen with links that I've added recently but there are quite a few old links that have a lot of duplicates and no easy means to remove them.

Just wanted to know about this before I considered moving over. Thank you!

**Comment by peteretelej** [comment]
doesn't allow duplicate bookmark urls https://github.com/RadhiFadlillah/shiori/blob/df7d08a75bb8207915bdd06696c9b835b84d9b3d/database/sqlite.go#L57

**Comment by karanrajpal14** [comment]
Great! Thank you very much!

**Comment by codeanpeace** [comment]
Assuming shiori doesn't automatically strip UTM params from the url before persisiting, a unique constraint on url doesn't equate to a unique constraint on content. The same page can map to many unique URLs because of UTM params. Pocket has this problem too...

**Comment by heliostatic** [comment]
@codeanpeace It doesn't yet, but #26 is to address that issue.
