### ISSUE TITLE
Would be nice to have a tag-cloud

### ISSUE THREAD

**Issue by skx** [RadhiFadlillah/shiori#16]
This is a beautiful project!  I've imported 500+ bookmarks and it can be a little hard to find what I want, when I'm not 100% sure.

I think it would be useful to change the "Reload" icon at the top-right with a link to a tag-cloud view.  A user who wants to reload could just use "F5" - unless I misunderstand what that link does.

Seeing all the tags in one place is likely to be a useful thing, and help show more data.  (Because the thumbnail view of the main index means it takes up a lot of space.)

**Comment by peteretelej** [comment]
> A user who wants to reload could just use "F5" - unless I misunderstand what that link does
the reload button doesn't perform a page reload. It updates the bookmark results via ajax

**Comment by skx** [comment]
Ahh I misunderstood its purpose then!  But regardless it would be nice to see a tag list/cloud page.

**Comment by skx** [comment]
Looks like this has been implemented in :+1: 

* https://github.com/RadhiFadlillah/shiori/pull/49

I'll close.

**Comment by RadhiFadlillah** [comment]
@skx I've merged it in [eee3dc7](https://github.com/RadhiFadlillah/shiori/commit/eee3dc75c20a775e5b8fbb740490765518111377). Could you check it out ?

**Comment by skx** [comment]
Looks great, I'm happy to close this.

I'm sure I'm not alone in appreciating how responsive you've been to issues and pull-requests.  :)
