### ISSUE TITLE
Unable to put empty string as excerpt

### ISSUE THREAD

**Issue by sascha-andres** [RadhiFadlillah/shiori#18]
The excerpt extraction for `https://www.programming-books.io/essential/go/` does not work as expected.

It displays `↑ ↓ to navigate ↵ to select Esc to close` and even when I edit the excerpt to have it empty, it fills in the excerpt again.

My expected behaviour would have been to be able to set the excerpt explicitly to an empty string

**Comment by peteretelej** [comment]
Empty excerpts seem to be overwritten during update https://github.com/RadhiFadlillah/shiori/blob/3826d4b7ab346a539ea3457c1402b19ea68b4f71/cmd/update.go#L149-L151 
whitespace characters are also trimmed during input, hence will be overwritten.
https://github.com/RadhiFadlillah/shiori/blob/3826d4b7ab346a539ea3457c1402b19ea68b4f71/view/index.html#L74
also applies for the title. I think deleting the excerpt at least would be nice, maybe an additional table column for deletedexcerpt, or using a character like '-' for deleted excerpts and replacing when displaying/reading

**Comment by RadhiFadlillah** [comment]
Fixed in [9d3c8ee](https://github.com/RadhiFadlillah/shiori/commit/9d3c8eedf9379edd3ab2bce974e912f4b579ae97).
