### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by peteretelej** [RadhiFadlillah/shiori#19]
Set up tests, at least for ./cmd 

Can work on this.

**Comment by skx** [comment]
Good pull-request, but I suspect you really _should_ update the sqlite handler to allow a filename to be specified - then use a temporary file.

Otherwise you risk blowing away a users valid `shiori.db` file.

**Comment by peteretelej** [comment]
Yeah, I think a filename passed to `db.OpenSQLiteDatabase` would be best. 

Though, the TestMain's tear only runs for package cmd, so unless one runs `./shiori` in cmd, it won't affect the main db file. 

In any case, let me update the PR with the filename arg.
