### ISSUE TITLE
Import doesn't populate tags

### ISSUE THREAD

**Issue by vaskas** [RadhiFadlillah/shiori#28]
Running `shiori import test.html` (from the uncompressed attachment) doesn't add tags to the links.

[test.zip](https://github.com/RadhiFadlillah/shiori/files/1775909/test.zip)

**Comment by RadhiFadlillah** [comment]
Should be fixed by [837c470](https://github.com/RadhiFadlillah/shiori/commit/837c4701760dc479be7e0b4b7dabe2f1408b1be0).

**Comment by vaskas** [comment]
Thanks Radhi! Import now works well for bookmarks with tags.

However those not having tags have the following side effect:
![screenshot-localhost 8080-2018-03-04-14-16-20](https://user-images.githubusercontent.com/67034/36941761-1cb2561a-1fb7-11e8-929a-72ac3e70b82d.png)

This is not something you get when simply adding a bookmark:
![screenshot-localhost 8080-2018-03-04-14-18-44](https://user-images.githubusercontent.com/67034/36941760-1cb12358-1fb7-11e8-9b1f-9278ece16c19.png)

**Comment by RadhiFadlillah** [comment]
Doh, it should be fixed by [24bdec2](https://github.com/RadhiFadlillah/shiori/commit/24bdec2c05b5facbb7c1e0fe3f33f812a294de6e).
