### ISSUE TITLE
Change Request: Don't update the index of bookmarks when deleting

### ISSUE THREAD

**Issue by heliostatic** [RadhiFadlillah/shiori#30]
Today, if you delete a bookmark, it could change the index of other bookmarks. 

That changes the cache URL of other bookmarks, which can lead to surprising results if you've recorded that URL somewhere else.

**Comment by RadhiFadlillah** [comment]
Oh yeah, that's true, I haven't thought that far ahead. I make the index changed after delete only because [`buku`](https://github.com/jarun/Buku) does it. 

I will remove it as soon as possible.

**Comment by heliostatic** [comment]
Ah, makes sense. Hadn't seen Buku. Really liking Shiori, thanks for your work!

**Comment by RadhiFadlillah** [comment]
I've removed it in [46c88d5](https://github.com/RadhiFadlillah/shiori/commit/46c88d5db5d44a2648e22016bd4cddf795524363).
