### ISSUE TITLE
Optional title isn't optional in the web view on unauthorized links

### ISSUE THREAD

**Issue by csterritt** [RadhiFadlillah/shiori#31]
Hello,

First, thanks for doing this!  It's pretty impressive.

However, the web-page view has a form that expands when you enter a new URL, with the title field having the placeholder text "Custom bookmark title (optional)".  When you save without a title, it works fine, unless the URL returns "unauthorized".  Then you're told "Title must not empty".

I accidentally set up a link to a page that requires a login, and saw this.

**Comment by RadhiFadlillah** [comment]
Hi @csterritt, sorry for late response. Thanks for using and reporting this issue.

Yeah, that is intended actually. When user omits the title, `shiori` will fetch the webpage and parse the title. When the webpage is unreachable, `shiori` is supposed to use the custom title, and if the custom title is empty as well, `shiori` will show that error message.

I guess I will add more information to error message. So, from :

```
Title must not empty
```

I will change it to :`

```
Webpage is unreachable. Please add custom title.
```

**Comment by csterritt** [comment]
@RadhiFadlillah That sounds like a great solution!  It'll be obvious, then, what is wrong -- that would have helped me a lot, to figure out what I'd done wrong.

**Comment by RadhiFadlillah** [comment]
Hi @csterritt.

By the latest commit ([`ecbc92d`](https://github.com/RadhiFadlillah/shiori/commit/ecbc92d24c5d76c3edf5daab96726a01fdded95d)), I've changed the default behaviour when URL is unreachable. Now, instead forcing user to input custom title, `shiori` will use the submitted URL as the title for the new bookmark. This way, I think it will be simpler and predictable for user. Besides, user can easily change the title of the URL in later time.

**Comment by csterritt** [comment]
@RadhiFadlillah Sounds good!
