### ISSUE TITLE
Feature Request: Tag autocompletion

### ISSUE THREAD

**Issue by mesuutt** [RadhiFadlillah/shiori#33]
Tag auto completion for users which has hundreds of tags should be good.
Also using comma instead of space for tagging should be good.

**Comment by RadhiFadlillah** [comment]
I've added simple auto complete in commit [`9fa4cb2`](https://github.com/RadhiFadlillah/shiori/commit/9fa4cb24523e17578ac746fdd40d303c0067f8be). Do note it only works in the main page and not from bookmarklet :

![peek 2018-06-07 14-17](https://user-images.githubusercontent.com/6129042/41084494-93744e56-6a5e-11e8-97ba-7e66afb10046.gif)

**Comment by RadhiFadlillah** [comment]
I’m closing this issue because :

- It has been implemented, and;
- It has been inactive for a while, so I guess this issue has been solved. 

Feels free to reopen it if needed.

Thank you.
