### ISSUE TITLE
Feature Request: Ability to Specify Database Location

### ISSUE THREAD

**Issue by Kr4ken-9** [RadhiFadlillah/shiori#36]
Recently, I was using shiori from different locations, and realized that a database is created where I use it on-demand. It would be useful if I could specify a static location to store the database, maybe through a parameter.

**Comment by RadhiFadlillah** [comment]
Yeah, there is already PR #3 that want to solve it, however I still checking on it. Should be merged soon though.

**Comment by RadhiFadlillah** [comment]
@Kr4ken-9 sorry for late reply. This feature has been merged in [1338a44](https://github.com/RadhiFadlillah/shiori/commit/1338a443cd4b031fb8b25c069222f7f49a02c8df). Now, you can set the database path by setting environment variable `ENV_SHIORI_DB`.

**Comment by Kr4ken-9** [comment]
Awesome! Thank you @RadhiFadlillah and @sascha-andres !
