### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by vaskas** [RadhiFadlillah/shiori#4]
Trying to import the attached file (unarchived) results in no new entries. Tried it with a bigger file too (500+ entries).

[test.zip](https://github.com/RadhiFadlillah/shiori/files/1770697/test.zip)

**Comment by RadhiFadlillah** [comment]
Thanks for the issue. Could you test it again ? It should be fixed by [`259d1b9`](https://github.com/RadhiFadlillah/shiori/commit/259d1b96ed6961d18903814c161a6170deaf4172).

**Comment by vaskas** [comment]
Yep, this has been fixed. Thanks!
