### ISSUE TITLE
Frontend has a horizontal scrollbar

### ISSUE THREAD

**Issue by Hunter-Github** [RadhiFadlillah/shiori#43]
**Version**:  commit 837c4701760dc479be7e0b4b7dabe2f1408b1be0
**OS**: Linux (Debian 9)
**Browser**:  Chromium 66.0.3357.0

**Problem**: The application's web page forces the user to scroll horizontally, which is not ergonomically efficient.
**Reproducibility**: have not tried (no FF/Safari/IE at the moment).

**Possible underlying problem**: card names are too long for a three-column layout to fit the screen width.

**Comment by RadhiFadlillah** [comment]
Fixed in [d735ca1](https://github.com/RadhiFadlillah/shiori/commit/d735ca1f8b04db50b153fc7c155692a4f5de6f41).
