### ISSUE TITLE
Broken layout on unbroken text

### ISSUE THREAD

**Issue by peteretelej** [RadhiFadlillah/shiori#54]
Long unbroken text in bookmark title, url, excerpt break layout of page.

**Fix**: adding `word-break: break-all;` to `.bookmark-title`, `bookmark-url` and `bookmark-excerpt` in stylesheet.less / css.

![screenshot from 2018-03-06 20-21-02](https://user-images.githubusercontent.com/2271973/37047954-8d6252a8-217d-11e8-9b2e-a214691043d3.png)

Tried fixing, but building with fileb0x was too hard :man_shrugging:

**Comment by peteretelej** [comment]
Would also most likely fix #43 (card names are too long for a three-column layout )

**Comment by RadhiFadlillah** [comment]
Hey @peteretelej, thanks for the report.

Yeah, this issue is the same with #43. It's only happened in Chrome because it doesn't support `hyphens: auto`. I've fixed it in [d735ca1](https://github.com/RadhiFadlillah/shiori/commit/d735ca1f8b04db50b153fc7c155692a4f5de6f41).
