### ISSUE TITLE
Cache not working?

### ISSUE THREAD

**Issue by tomas** [RadhiFadlillah/shiori#55]
Hi, just installed shiori on a server and trying it out. Looks great!

Unfortunately, I added a few bookmarks and none of them generated any cached versions. In what conditions does this happen? Is there some dependency that I have to install on my server? 

Thanks

**Comment by RadhiFadlillah** [comment]
Hi @tomas, thanks for using this app and reporting this issue.

> Is there some dependency that I have to install on my server ?

No, there are no dependency needed.

> I added a few bookmarks and none of them generated any cached versions. In what conditions does this happen?

Normally, `shiori` should fetch the content by default. May I know how you add the bookmark ? Using command line, web interface or using `shiori import` ? If possible, could you give me the URL where `shiori` doesn't fetch any content ?

Thank you.

**Comment by tomas** [comment]
Via the web interface, although I did try updating the link afterwards from the command line. 

One of the links I tried was this small HTML page:

https://tinyapps.org/system.html

**Comment by RadhiFadlillah** [comment]
Hi @tomas, could you check it again ?

The caching process is done by [go-readability](https://github.com/RadhiFadlillah/go-readability), and I've push the fix at [9724ab](https://github.com/RadhiFadlillah/go-readability/commit/9724ab1cb1c74bebffc3db4344fa277852c67f77).

**Comment by tomas** [comment]
It works! However, links in the copied HTML are all wrong (they're somehow prepending the original link's hostname in them):

![image](https://user-images.githubusercontent.com/10574/37151774-b5e9eb62-22b5-11e8-91c5-2d6c3873bd37.png)

**Comment by RadhiFadlillah** [comment]
Fixed in [go-readability#558d9b4](https://github.com/RadhiFadlillah/go-readability/commit/558d9b48d988df9ee317530a104890b6a8c5b9a7).

**Comment by tomas** [comment]
Great, thanks.

Not related, but, would it be possible to have a bookmark added just by entering a URL and hitting the enter key? Having to use the mouse and click the "Done" button affects usability IMHO.

**Comment by tomas** [comment]
Oh and it looks like go-readability's content lookup doesn't work always. Here's another URL where I get an empty result: https://www.plop.at/en/bootmanager/index.html

**Comment by RadhiFadlillah** [comment]
> Not related, but, would it be possible to have a bookmark added just by entering a URL and hitting the enter key? Having to use the mouse and click the "Done" button affects usability IMHO.

Yeah, it's in the future plan.

> Oh and it looks like go-readability's content lookup doesn't work always. Here's another URL where I get an empty result.

Yeah, it's still in development and I haven't finished porting the entire methods from [`mozilla/readability`](https://github.com/mozilla/readability). There are some parts of code that I find quite hard to port, especially since Go and JS have opposite character (static vs dynamic language), so PR and contributions are always welcome.

BTW, since `go-readability` is port of `mozilla/readability` (which powers reader mode in Firefox), that means if Firefox unable to render the readable format for a website, most likely `go-readability` can't do it as well.

**Comment by tomas** [comment]
I see. golang isn't my weapon of choice, so unfortunately I cannot help you much with PRs in `go-readability`. Thanks again!
