### ISSUE TITLE
Updating missing metadata only

### ISSUE THREAD

**Issue by muesli** [RadhiFadlillah/shiori#58]
I've imported hundreds of bookmarks from delicious and I'd like to import pictures and cache those pages (ideally in batch-mode). Clicking the `update` button in the web interface does that, but it also updates the title of my bookmark. Is there a way to only fetch missing metadata?

**Comment by RadhiFadlillah** [comment]
Hi @muesli, I've added this feature int [f4911d](https://github.com/RadhiFadlillah/shiori/commit/f4911d33a98f5050bd08be1cc916eaf9ee272d31). Could you check it out ?

**Comment by muesli** [comment]
Seems to work fine!
