### ISSUE TITLE
Missing assets folder

### ISSUE THREAD

**Issue by x2764tech** [RadhiFadlillah/shiori#6]
I can't build this as there's a missing `assets` package, referenced from [serve.go](https://github.com/RadhiFadlillah/shiori/blob/master/cmd/serve.go#L8)

**Comment by Zhann** [comment]
have this very same issue

**Comment by cron410** [comment]
its in .gitignore, which keeps it from being pushed from the author's local Git repo into this one.

**Comment by RadhiFadlillah** [comment]
Man, it's embarassing. Yeah, the `assets` folder is supposed to be generated by `go:generate`. I forgot `go import` doesn't run it.

**Comment by skx** [comment]
I can confirm that this now works, so this issue can be closed :)

**Comment by RadhiFadlillah** [comment]
> I can confirm that this now works, so this issue can be closed :)

Thanks for the confirmation.
