### ISSUE TITLE
Is it possible to support HTTPs ?

### ISSUE THREAD

**Issue by maplebeats** [RadhiFadlillah/shiori#62]
看了一下源码用的标准http库，可以在serve里增加https支持，会不会更好些

---

I looked at the source code and it seems `shiori` is using standard http server. I think it will be better if you can add https support in the `serve`.

**Comment by RadhiFadlillah** [comment]
I don't think `shiori` need to support HTTPs. The reasons are :

- I think most of the time `shiori` is only used as cli or in localhost, which doesn't need HTTPs.
- If used in server, `shiori` can be used behind another web server like `caddy` (which already provide HTTPs by default) or `nginx`.
