### ISSUE TITLE
Add automatic Docker build

### ISSUE THREAD

**Issue by maxmeyer** [RadhiFadlillah/shiori#67]
If either #27 or #66 are merged, please setup an automatic "Docker build" on hub.docker.com. BTW: #66 assumes, that your account on hub.docker.com is "radhifadlillah" - lower case is required by docker.

**Comment by RadhiFadlillah** [comment]
Hi @maxmeyer thanks for the PR.

I've never use Docker before, that's why I've put off merging those PRs while I learning at least the basic of Docker. It should be merged soon though.

**Comment by maxmeyer** [comment]
@RadhiFadlillah Thanks for the feedback. Feel free to ask if something is unclear or you get stuck.

**Comment by RadhiFadlillah** [comment]
Done by PR #66.
