### ISSUE TITLE
Does Web GUI not supports adding a bookmark?

### ISSUE THREAD

**Issue by mingrammer** [RadhiFadlillah/shiori#71]
Should I add a bookmark using only CLI? There seems no add feature on Web GUI

**Comment by BoundsCheck** [comment]
Just type/paste the URL into the box where it says 'URL for the new bookmark', it's at the top under the 'search tags' box

**Comment by mingrammer** [comment]
Ah .. I didn't see the `URL for the new bookmark` text. Why did I read it `There is no bookmarks` :( .. Sorry for that.

Thanks ..
