### ISSUE TITLE
Default location for shiori database

### ISSUE THREAD

**Issue by sorbits** [RadhiFadlillah/shiori#72]
I would suggest using the user’s home directory for the default location of the shiori database.

I call shiori from different contexts where “current directory” is not well-defined (nor the same).

I know I can set `ENV_SHIORI_DB` but since I am on macOS this is a bit tedious because GUI applications do not inherit environment variables setup in the shell, so this will need to be set in multiple places.

If you agree I suggest prefixing it with a dot to make it a hidden file, e.g. `~/.shiori_db`.

I realize this might be very unixy, but it already seems rather unixy with a shell command to manage your bookmarks.

**Comment by RadhiFadlillah** [comment]
Hi @sorbits, I've added this feature in [6bab302](https://github.com/RadhiFadlillah/shiori/commit/6bab302785263e942ee50421fda500316fa253b0). Could you check it out ?

**Comment by sorbits** [comment]
Thanks a lot, works as expected!
