### ISSUE TITLE
Suggestion: use gox for cross compile

### ISSUE THREAD

**Issue by iawia002** [RadhiFadlillah/shiori#75]
In release page, you wrote:
> Thanks to Go, this app should work in Windows, MacOS and Linux. However, since I only able to test it in my workstation, I only put the binary for Linux 64-bit. Sorry for the inconvenience.

I think [gox](https://github.com/mitchellh/gox) can solve this problem for you

**Comment by maxmeyer** [comment]
`gox` is used for build - [.travis.yml](https://github.com/RadhiFadlillah/shiori/blob/master/.travis.yml#L23), maybe this change a while back.

**Comment by iawia002** [comment]
Cool!
