### ISSUE TITLE
Tab interaction is not intuitive

### ISSUE THREAD

**Issue by Hunter-Github** [RadhiFadlillah/shiori#79]
Login screen: Tab doesn't move to `Login` button after the password is entered.
Main screen: Tab moves vertically along the column (this one is iffy, can be argued either way, but goes against the usual visual scan order).
Edit bookmark form: Tab doesn't move to `Cancel`/`Done` but simply jumps to the next visible card in the first column. This one breaks user expectations.

Version: 6bab302785263e942ee50421fda500316fa253b0

**Comment by RadhiFadlillah** [comment]
It should be fixed in the latest commit [`ecbc92`](https://github.com/RadhiFadlillah/shiori/commit/ecbc92d24c5d76c3edf5daab96726a01fdded95d).

**Comment by RadhiFadlillah** [comment]
Hi @Hunter-Github, I’m closing this issue for now because :

- It has been implemented, and;
- It has been inactive for a while, so I guess this issue has been solved. 

Feels free to reopen it if needed.

Thank you.
