### ISSUE TITLE
Account and bookmark disappearance

### ISSUE THREAD

**Issue by dxwc** [RadhiFadlillah/shiori#80]
I was trying out the [released binary](https://github.com/RadhiFadlillah/shiori/releases/download/v1.0/shiori) yesterday, it seems to have been working fine. After restarting the computer today, the account to login to the `shiori serve` is gone. All but one bookmark I created yesterday is gone as well.

`shiori print` seems to be working a bit unpredictably as well, one time it prints this :

```
panic: unable to open database file

goroutine 1 [running]:
github.com/jmoiron/sqlx.MustConnect(0x9fcc1e, 0x7, 0x9fedc6, 0x9, 0xc4201ddf28)
	/home/radhi/GoProjects/src/github.com/jmoiron/sqlx/sqlx.go:640 +0x83
github.com/RadhiFadlillah/shiori/database.OpenSQLiteDatabase(0x0, 0x0, 0x0)
	/home/radhi/GoProjects/src/github.com/RadhiFadlillah/shiori/database/sqlite.go:24 +0x82
main.main()
	/home/radhi/GoProjects/src/github.com/RadhiFadlillah/shiori/main.go:11 +0x26
```

Other time, it's working fine (but still prints one of the bookmarks instead of all that I created yesterday). 

`/home/radhi/GoProjects/src/github.com/jmoiron/sqlx/sqlx.go` isn't any matching directory in my computer. Maybe some debugging settings made into the release ?

-----

+ Gnome: 3.26.2
+ Solus: 3.99
+ To run, I placed the binary in `/usr/local/bin/` and did a `sudo chmod +x shiori`

**Comment by RadhiFadlillah** [comment]
@dxwc sorry for late reply. Could you try to update to latest version. It should be fixed by now.

**Comment by dxwc** [comment]
@RadhiFadlillah I have been using it for last two days. No such problems so far. Thanks

**Comment by dxwc** [comment]
@RadhiFadlillah I have been using it for last two days. No such problems so far. Thanks
