### ISSUE TITLE
Display bookmark index in the web interface

### ISSUE THREAD

**Issue by gissehel** [RadhiFadlillah/shiori#88]
I often use both the web interface and the command line interface.

I search using the web interface, and update using the command line. But adding/removing tags using the command line require the bookmark index that is not displayed in the web interface.

It would be usefull to have the index somewhere in the bookmark panel.

**Comment by gissehel** [comment]
I've updated the pull request #89 for the new UI

**Comment by RadhiFadlillah** [comment]
Hi @gissehel, thanks and sorry for late response.

Since PR #89 has been merged, I will close this issue for now.
