### ISSUE TITLE
Installation isn't working

### ISSUE THREAD

**Issue by deadcoder0904** [RadhiFadlillah/shiori#9]
I tried PR #8 instructions but it isn't working

I am a `NodeJS` developer but I know how to install with `GoLang`

So I installed `Go` with `brew install go` & `go version` gives me `go version go1.10 darwin/amd64`

Then I did `go get github.com/RadhiFadlillah/shiori` & when I try `shiori` it gives me `zsh: command not found: shiori`

**Comment by deadcoder0904** [comment]
It installs it in `~/go/bin/shiori`

**Comment by deadcoder0904** [comment]
Found solution from http://avi.im/blag/2016/install-go-sierra/

**Comment by muesli** [comment]
Just start the binary from there or add ~/go/bin to your `$PATH`.

**Comment by deadcoder0904** [comment]
Yep got it working. I thought `brew install go` does all the job of installing `Go` & adding to the `$PATH` but it doesn't add to the `$PATH`.
