### ISSUE TITLE
Commit ec53fe61 breaks usage of ENV_SHIORI_DB

### ISSUE THREAD

**Issue by intabulas** [RadhiFadlillah/shiori#93]
I use the env var to put my DB on dropbox, with the latest set of changes, that env var is totally ignored.  On OSX the db is forcibly created on ~r/Library/Application Support/shiori but the readme still refers to (and the dockerfile references) the env var

This might cause some headaches for people upgrading or who use the env var to have portability between devices

**Comment by sascha-andres** [comment]
If you set ENV_SHIORI_DIR to just the directory and name the file shiori.db it should work
