### ISSUE TITLE
is this library api based, if i want to use PHP instead of GO?

### ISSUE THREAD

**Issue by rajjanorkar** [RadhiFadlillah/shiori#96]
is this library api based, if i want to use PHP instead of GO?

**Comment by RadhiFadlillah** [comment]
Hi @rajjanorkar, sorry for late reply.

Shiori does have a REST API that you get after running `shiori serve`. There are several endpoints available that you can see [here](https://github.com/RadhiFadlillah/shiori/blob/master/cmd/serve/root.go#L15).

**Comment by rajjanorkar** [comment]
Thank you for your reply. I will investigate it further to see how i can do it.

**Comment by RadhiFadlillah** [comment]
Since it has been inactive for a while, I will close this issue for now. Feels free to reopen it if needed.

Thank you.

**Comment by rajjanorkar** [comment]
Hi @RadhiFadlillah 

i have created this repository [Bookmark-Manager](https://github.com/bookmarkapp/bookmark-manager) for web application.

I have taken your vuejs component and plugged it into laravel backend app. 

Thank you
